package metrics

import (
	"os"
	"testing"
	"time"
)

// This fixture follows the unit-bearing JSON contract defined by the official
// AMD-SMI CLI source. Values are synthetic contract data, not measurements.
func TestParseAMDSMIJSONReadsEveryDevice(t *testing.T) {
	output, err := os.ReadFile("testdata/amd_smi_two_gpus.json")
	if err != nil {
		t.Fatalf("cannot read fixture: %v", err)
	}

	now := time.Unix(1754784000, 0)
	samples, err := parseAMDSMIJSON(output, now)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(samples) != 2 {
		t.Fatalf("expected two GPUs, got %d", len(samples))
	}

	first := samples[0]
	if first.DeviceID != 0 || first.Vendor != GPUVendorAMD || first.GPUUtilization != 91 {
		t.Errorf("first GPU identity/utilization misread: %+v", first)
	}
	if first.MemoryUsedMB != 24576 || first.MemoryTotalMB != 65536 || first.MemoryUtilization != 37.5 {
		t.Errorf("first GPU memory misread: %+v", first)
	}
	if first.PowerUsageW != 228.75 || first.TemperatureC != 63 {
		t.Errorf("first GPU thermals/power misread: %+v", first)
	}
	if first.ClockSpeedMHz != 1725 || first.MemoryClockMHz != 1600 {
		t.Errorf("first GPU clocks misread: %+v", first)
	}
	if !first.Timestamp.Equal(now) {
		t.Errorf("timestamp = %v, want %v", first.Timestamp, now)
	}

	second := samples[1]
	if second.DeviceID != 1 || second.MemoryUsedMB != 8192 || second.MemoryTotalMB != 32768 {
		t.Errorf("byte-valued memory misread: %+v", second)
	}
	if second.TemperatureC != 70 || second.PowerUsageW != 0 || second.MemoryClockMHz != 1100 {
		t.Errorf("fallback values misread: %+v", second)
	}
}

func TestParseAMDSMIJSONAcceptsGPUDataWrapper(t *testing.T) {
	input := []byte(`{"gpu_data":[{"gpu":7,"usage":{"gfx_activity":{"value":42,"unit":"%"}}}]}`)
	samples, err := parseAMDSMIJSON(input, time.Now())
	if err != nil || len(samples) != 1 {
		t.Fatalf("wrapped output did not parse: %v (%+v)", err, samples)
	}
	if samples[0].DeviceID != 7 || samples[0].GPUUtilization != 42 {
		t.Errorf("wrapped GPU misread: %+v", samples[0])
	}
}

func TestParseAMDSMIJSONRejectsMalformedJSON(t *testing.T) {
	if _, err := parseAMDSMIJSON([]byte(`[{"gpu":`), time.Now()); err == nil {
		t.Fatal("expected malformed JSON to return an explicit error")
	}
}

// The fixture follows the exact cardN/key layout generated by the official
// ROCm-SMI CLI source. Values are synthetic contract data, not measurements;
// hardware validation therefore remains documented separately.
func TestParseROCmSMIJSONReadsEveryDevice(t *testing.T) {
	output, err := os.ReadFile("testdata/rocm_smi_two_gpus.json")
	if err != nil {
		t.Fatalf("cannot read fixture: %v", err)
	}

	now := time.Unix(1754784000, 0)
	samples, err := parseROCmSMIJSON(output, now)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(samples) != 2 {
		t.Fatalf("expected two GPUs, got %d", len(samples))
	}

	first := samples[0]
	if first.DeviceID != 0 || first.Vendor != GPUVendorAMD || first.DeviceName != "AMD Instinct MI210" {
		t.Errorf("first GPU identity misread: %+v", first)
	}
	if first.GPUUtilization != 87 || first.ComputeUtilization != 87 || first.MemoryUtilization != 25 {
		t.Errorf("first GPU utilization misread: %+v", first)
	}
	if first.MemoryUsedMB != 16384 || first.MemoryTotalMB != 65536 {
		t.Errorf("first GPU memory units misread: %+v", first)
	}
	if first.TemperatureC != 64 || first.PowerUsageW != 215.5 || first.PowerLimitW != 300 {
		t.Errorf("first GPU thermals/power misread: %+v", first)
	}
	if first.ClockSpeedMHz != 1700 || first.MemoryClockMHz != 1600 {
		t.Errorf("first GPU clocks misread: %+v", first)
	}
	if !first.Timestamp.Equal(now) {
		t.Errorf("timestamp = %v, want %v", first.Timestamp, now)
	}

	second := samples[1]
	if second.DeviceID != 1 || second.GPUUtilization != 12 {
		t.Errorf("second GPU misread: %+v", second)
	}
	if second.TemperatureC != 72 || second.PowerUsageW != 0 {
		t.Errorf("fallback temperature/N/A power misread: %+v", second)
	}
}

func TestParseROCmSMIJSONComputesMemoryPercentageWhenAbsent(t *testing.T) {
	input := []byte(`{"card0":{"VRAM Total Memory (B)":"4194304","VRAM Total Used Memory (B)":"1048576"}}`)
	samples, err := parseROCmSMIJSON(input, time.Now())
	if err != nil || len(samples) != 1 {
		t.Fatalf("fixture did not parse: %v (%+v)", err, samples)
	}
	if samples[0].MemoryUtilization != 25 {
		t.Errorf("memory utilization = %v, want 25", samples[0].MemoryUtilization)
	}
}

func TestParseROCmSMIJSONRejectsMalformedJSON(t *testing.T) {
	if _, err := parseROCmSMIJSON([]byte(`{"card0":`), time.Now()); err == nil {
		t.Fatal("expected malformed JSON to return an explicit error")
	}
}

func TestParseROCmSMIJSONReportsNothingWithoutCards(t *testing.T) {
	samples, err := parseROCmSMIJSON([]byte(`{"system":{"AMDGPU version":"6.4.0"}}`), time.Now())
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(samples) != 0 {
		t.Fatalf("expected no samples, got %+v", samples)
	}
}
